# Generated by Django 4.1.7 on 2023-04-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='staff1', max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
