# Generated by Django 4.1.7 on 2023-03-22 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='Address',
            new_name='address',
        ),
    ]
