# Generated by Django 4.1.7 on 2023-03-25 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('instructors', '0002_rename_address_instructor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licNum', models.CharField(max_length=100, unique=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='instructors.instructor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='programs.program')),
            ],
        ),
    ]
