# Generated by Django 4.1.7 on 2023-03-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0003_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('schedule', models.CharField(max_length=100)),
                ('begin', models.DateField(blank=True, max_length=100, null=True)),
                ('end', models.DateField(blank=True, max_length=100, null=True)),
                ('intBegin', models.DateField(blank=True, max_length=100, null=True)),
                ('intEnd', models.DateField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('intSite', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='instructors.license')),
            ],
        ),
    ]
