# Generated by Django 4.1.7 on 2023-04-15 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('begin', models.DateField(blank=True, max_length=100, null=True)),
                ('end', models.DateField(blank=True, max_length=100, null=True)),
                ('intBegin', models.DateField(blank=True, max_length=100, null=True)),
                ('intEnd', models.DateField(blank=True, max_length=100, null=True)),
                ('intSite', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='instructors.license')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='programs.program')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=30, unique=True)),
                ('dob', models.DateField(max_length=15)),
                ('lName', models.CharField(max_length=30)),
                ('fName', models.CharField(max_length=30)),
                ('last4Digits', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('accountInfo', models.CharField(blank=True, max_length=256, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='classes', to='classes.class')),
            ],
        ),
    ]
